services:
  - type: web
    name: telegram-fastapi
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PROCESS_ROLE
        value: web

  - type: worker
    name: telegram-bot-worker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -u run_bot.py
    envVars:
      - key: PROCESS_ROLE
        value: bot-worker
