(() => {
  const bank = [];
  const add = (id, category, question, choices, answer, fact) => {
    bank.push({ id, category, question, choices, answer, fact });
  };

  const seed = [
    ["g1", "general", "What is the capital of Kenya?", ["Nairobi", "Mombasa", "Kisumu", "Eldoret"], 0, "Nairobi is the capital city of Kenya."],
    ["g2", "general", "Which ocean is the largest?", ["Atlantic", "Indian", "Pacific", "Arctic"], 2, "The Pacific Ocean is the largest ocean on Earth."],
    ["g3", "general", "How many days are in a leap year?", ["364", "365", "366", "367"], 2, "Leap years include 366 days."],
    ["g4", "general", "Which continent is Egypt part of?", ["Africa", "Asia", "Europe", "South America"], 0, "Egypt is in northeastern Africa."],
    ["g5", "general", "Which country is famous for the city of Tokyo?", ["China", "Japan", "South Korea", "Thailand"], 1, "Tokyo is the capital of Japan."],
    ["g6", "general", "What do bees make?", ["Silk", "Honey", "Wax paper", "Milk"], 1, "Bees are known for making honey from nectar."],
    ["g7", "general", "Which planet is known as the Red Planet?", ["Mercury", "Venus", "Mars", "Jupiter"], 2, "Mars appears red because of iron oxide on its surface."],
    ["g8", "general", "What is the tallest type of grass?", ["Bamboo", "Wheat", "Rice", "Corn"], 0, "Bamboo is technically a giant grass."],
    ["g9", "general", "Which month has the fewest days?", ["February", "April", "June", "November"], 0, "February has 28 days in most years."],
    ["g10", "general", "Which instrument has black and white keys?", ["Drum", "Violin", "Piano", "Trumpet"], 2, "A piano keyboard uses black and white keys."],
    ["g11", "general", "What is the main language spoken in Brazil?", ["Spanish", "Portuguese", "French", "English"], 1, "Portuguese is Brazil's official language."],
    ["g12", "general", "Which desert is the largest hot desert in the world?", ["Gobi", "Sahara", "Kalahari", "Arabian"], 1, "The Sahara is the world's largest hot desert."],
    ["g13", "general", "Which sport uses a bat, a ball, and wickets?", ["Baseball", "Cricket", "Tennis", "Golf"], 1, "Cricket is played with a bat, a ball, and wickets."],
    ["g14", "general", "Which country gifted the Statue of Liberty to the United States?", ["Italy", "Spain", "France", "Canada"], 2, "France gifted the Statue of Liberty in 1886."],
    ["g15", "general", "What is the freezing point of water in degrees Celsius?", ["0", "10", "32", "100"], 0, "Water freezes at 0 degrees Celsius."],
    ["g16", "general", "Which animal is known as the king of the jungle?", ["Tiger", "Elephant", "Lion", "Gorilla"], 2, "The lion is commonly called the king of the jungle."],
    ["g17", "general", "How many continents are there?", ["5", "6", "7", "8"], 2, "There are seven continents."],
    ["g18", "general", "What color do you get when you mix blue and yellow?", ["Purple", "Green", "Orange", "Brown"], 1, "Blue and yellow make green."],
    ["g19", "general", "Which country is home to the pyramids of Giza?", ["Mexico", "Peru", "Egypt", "Jordan"], 2, "The pyramids of Giza are in Egypt."],
    ["g20", "general", "Which metal is liquid at room temperature?", ["Mercury", "Silver", "Copper", "Gold"], 0, "Mercury is liquid at standard room temperature."],

    ["s1", "science", "What gas do plants absorb from the air?", ["Oxygen", "Carbon dioxide", "Nitrogen", "Hydrogen"], 1, "Plants absorb carbon dioxide during photosynthesis."],
    ["s2", "science", "What is the center of the solar system?", ["Earth", "Moon", "Sun", "Mars"], 2, "The Sun is at the center of the solar system."],
    ["s3", "science", "What part of the human body pumps blood?", ["Lungs", "Brain", "Liver", "Heart"], 3, "The heart pumps blood through the body."],
    ["s4", "science", "What is H2O commonly called?", ["Hydrogen", "Salt", "Water", "Oxygen"], 2, "H2O is the chemical formula for water."],
    ["s5", "science", "Which organ helps humans breathe?", ["Kidney", "Lungs", "Stomach", "Skin"], 1, "The lungs help exchange oxygen and carbon dioxide."],
    ["s6", "science", "What force pulls objects toward Earth?", ["Magnetism", "Pressure", "Gravity", "Friction"], 2, "Gravity pulls objects toward Earth."],
    ["s7", "science", "What is the boiling point of water in degrees Celsius?", ["50", "75", "100", "150"], 2, "Water boils at 100 degrees Celsius at standard pressure."],
    ["s8", "science", "Which blood cells help fight infection?", ["Red blood cells", "White blood cells", "Platelets", "Plasma cells"], 1, "White blood cells help the body fight infection."],
    ["s9", "science", "Which planet has the most rings?", ["Earth", "Mars", "Saturn", "Venus"], 2, "Saturn is famous for its ring system."],
    ["s10", "science", "What is the hardest natural substance?", ["Iron", "Diamond", "Quartz", "Granite"], 1, "Diamond is the hardest natural substance."],
    ["s11", "science", "Which vitamin is mainly produced when skin gets sunlight?", ["Vitamin A", "Vitamin C", "Vitamin D", "Vitamin K"], 2, "Sunlight helps the body produce vitamin D."],
    ["s12", "science", "Which part of a cell contains genetic material?", ["Membrane", "Nucleus", "Cytoplasm", "Ribosome"], 1, "The nucleus stores most genetic material in eukaryotic cells."],
    ["s13", "science", "What do you call animals that eat only plants?", ["Carnivores", "Omnivores", "Herbivores", "Insectivores"], 2, "Herbivores eat plants."],
    ["s14", "science", "Which layer protects Earth from harmful ultraviolet rays?", ["Ionosphere", "Ozone layer", "Troposphere", "Cloud layer"], 1, "The ozone layer absorbs much of the Sun's ultraviolet radiation."],
    ["s15", "science", "What is the nearest star to Earth?", ["Sirius", "Alpha Centauri", "The Sun", "Polaris"], 2, "The Sun is Earth's nearest star."],
    ["s16", "science", "Which simple machine is a sloping surface?", ["Pulley", "Wheel", "Inclined plane", "Lever"], 2, "An inclined plane is a sloped flat surface."],
    ["s17", "science", "Which planet is the largest in our solar system?", ["Jupiter", "Saturn", "Earth", "Neptune"], 0, "Jupiter is the largest planet in the solar system."],
    ["s18", "science", "What is the process of liquid water turning into vapor called?", ["Condensation", "Evaporation", "Freezing", "Melting"], 1, "Evaporation turns liquid water into gas."],
    ["s19", "science", "Which body part contains the smallest bones in the human body?", ["Hand", "Ear", "Foot", "Jaw"], 1, "The middle ear contains the smallest bones."],
    ["s20", "science", "What kind of energy is stored in food?", ["Chemical energy", "Sound energy", "Light energy", "Nuclear energy"], 0, "Food stores chemical energy."],

    ["t1", "technology", "What does CPU stand for?", ["Central Processing Unit", "Computer Power Utility", "Central Print Unit", "Core Program Unit"], 0, "CPU stands for Central Processing Unit."],
    ["t2", "technology", "Which device is used to move the pointer on many desktop computers?", ["Scanner", "Mouse", "Speaker", "Projector"], 1, "A mouse is commonly used to control the pointer."],
    ["t3", "technology", "What does URL stand for?", ["Uniform Resource Locator", "Universal Record Link", "Unified Routing List", "User Resource Label"], 0, "URL stands for Uniform Resource Locator."],
    ["t4", "technology", "Which company created the Android operating system?", ["Apple", "Microsoft", "Google", "IBM"], 2, "Google develops Android."],
    ["t5", "technology", "What is used to store files long term in a computer?", ["RAM", "Storage drive", "Fan", "GPU"], 1, "Storage drives keep files after power is turned off."],
    ["t6", "technology", "What type of device is a router?", ["Input device", "Networking device", "Display device", "Audio device"], 1, "A router directs network traffic between devices."],
    ["t7", "technology", "Which key combination is often used to copy selected text on Windows?", ["Ctrl + C", "Ctrl + V", "Ctrl + X", "Ctrl + Z"], 0, "Ctrl + C copies selected text on many systems."],
    ["t8", "technology", "Which programming language runs natively in web browsers?", ["Python", "JavaScript", "C", "Rust"], 1, "JavaScript is the standard browser scripting language."],
    ["t9", "technology", "What does Wi-Fi mainly provide?", ["Wireless internet access", "Printed pages", "Longer battery life", "More storage"], 0, "Wi-Fi provides wireless network access."],
    ["t10", "technology", "What is phishing?", ["A type of monitor", "A cyber scam for stealing information", "A search engine", "A coding language"], 1, "Phishing tricks people into revealing sensitive information."],
    ["t11", "technology", "Which file type is commonly used for images?", [".jpg", ".mp3", ".txt", ".csv"], 0, "JPG is a common image file format."],
    ["t12", "technology", "What does HTML stand for?", ["HyperText Markup Language", "HighText Machine Language", "Hyper Transfer Markup Link", "Home Tool Markup Language"], 0, "HTML stands for HyperText Markup Language."],
    ["t13", "technology", "Which part of a phone displays the battery level, signal, and time?", ["Status bar", "Keyboard", "Camera", "Dock"], 0, "The status bar usually shows time, battery, and signal information."],
    ["t14", "technology", "What does a QR code do?", ["Stores a paper document", "Encodes information for scanning", "Improves sound quality", "Cools a device"], 1, "A QR code encodes information that a camera can scan."],
    ["t15", "technology", "Which tool helps keep online accounts safer by storing and creating passwords?", ["Password manager", "Media player", "Spreadsheet", "Calendar app"], 0, "Password managers help create and store strong passwords."],
    ["t16", "technology", "What is cloud storage?", ["Files saved on remote servers", "Files printed on paper", "A type of keyboard", "A hardware cable"], 0, "Cloud storage keeps files on remote internet-connected servers."],
    ["t17", "technology", "Which symbol is commonly used in email addresses?", ["#", "@", "$", "%"], 1, "The at sign is used in email addresses."],
    ["t18", "technology", "What is an operating system?", ["A photo editor", "Software that manages a device", "A graphics card", "A search engine"], 1, "An operating system manages hardware and software resources."],
    ["t19", "technology", "Which browser is made by Mozilla?", ["Chrome", "Edge", "Firefox", "Safari"], 2, "Mozilla develops Firefox."],
    ["t20", "technology", "What does USB stand for?", ["Universal Serial Bus", "Unified Storage Block", "User System Base", "Ultra Speed Board"], 0, "USB stands for Universal Serial Bus."],

    ["e1", "english", "Which word is a synonym for 'happy'?", ["Sad", "Joyful", "Angry", "Slow"], 1, "Joyful and happy have similar meanings."],
    ["e2", "english", "What punctuation mark ends a direct question?", ["Comma", "Question mark", "Colon", "Dash"], 1, "Questions usually end with a question mark."],
    ["e3", "english", "Choose the correct plural of 'child'.", ["Childs", "Childes", "Children", "Childrens"], 2, "The correct plural of child is children."],
    ["e4", "english", "Which word is an adjective?", ["Quickly", "Blue", "Run", "Softly"], 1, "Blue can describe a noun, so it is an adjective."],
    ["e5", "english", "Choose the correct sentence.", ["She go to school.", "She goes to school.", "She going to school.", "She gone to school."], 1, "The singular subject 'she' takes 'goes'."],
    ["e6", "english", "Which word means the opposite of 'ancient'?", ["Modern", "Old", "Historic", "Broken"], 0, "Modern is the opposite of ancient in this context."],
    ["e7", "english", "What is the past tense of 'write'?", ["Writed", "Written", "Wrote", "Writes"], 2, "The simple past tense of write is wrote."],
    ["e8", "english", "Which sentence uses a pronoun?", ["Maria opened the door.", "The red car stopped.", "They arrived early.", "Rain fell all night."], 2, "They is a pronoun."],
    ["e9", "english", "Which word is a verb?", ["Dance", "Garden", "Chair", "Pencil"], 0, "Dance can be an action verb."],
    ["e10", "english", "Choose the correctly spelled word.", ["Definately", "Definetely", "Definitely", "Definatly"], 2, "Definitely is the correct spelling."],
    ["e11", "english", "Which word is a noun?", ["Beautiful", "Happily", "Mountain", "Listen"], 2, "Mountain names a thing, so it is a noun."],
    ["e12", "english", "What does 'bilingual' mean?", ["Speaking two languages", "Reading very fast", "Writing poetry", "Using long words"], 0, "Bilingual means able to use two languages."],
    ["e13", "english", "Choose the correct contraction for 'do not'.", ["Dont", "Do'nt", "Don't", "D'not"], 2, "Don't is the correct contraction of do not."],
    ["e14", "english", "Which word best completes the sentence: 'The room was very ___, so everyone whispered.'", ["Noisy", "Quiet", "Bright", "Busy"], 1, "Whispering fits a quiet room."],
    ["e15", "english", "Which is a complete sentence?", ["Because the rain stopped.", "After the meeting.", "The class ended early.", "When the bell rang."], 2, "The class ended early has a complete subject and predicate."],
    ["e16", "english", "Choose the antonym of 'include'.", ["Add", "Contain", "Exclude", "Gather"], 2, "Exclude is the opposite of include."],
    ["e17", "english", "Which word is an adverb?", ["Brave", "Softly", "Stone", "Teacher"], 1, "Softly describes how something happens, making it an adverb."],
    ["e18", "english", "Which word means 'a short and interesting story about a real event or person'?", ["Anecdote", "Chapter", "Poem", "Index"], 0, "An anecdote is a short, interesting story about a real incident."],
    ["e19", "english", "Choose the correct possessive form.", ["The dogs bone", "The dog's bone", "The dog bone's", "The dogs' bone's"], 1, "The dog's bone shows that the bone belongs to one dog."],
    ["e20", "english", "What is the main purpose of a dictionary?", ["To provide word meanings", "To solve math problems", "To tell the time", "To draw diagrams"], 0, "A dictionary gives meanings, spellings, and usage information for words."]
  ];

  seed.forEach((item) => add(...item));

  const mathRows = [
    ["m1", "What is 12 + 8?", ["20", "18", "22", "16"], 0, "12 + 8 = 20."],
    ["m2", "What is 15 - 7?", ["6", "7", "8", "9"], 2, "15 - 7 = 8."],
    ["m3", "What is 9 x 6?", ["42", "54", "56", "63"], 1, "9 times 6 equals 54."],
    ["m4", "What is 49 divided by 7?", ["6", "7", "8", "9"], 1, "49 divided by 7 equals 7."],
    ["m5", "What is the value of 5 squared?", ["10", "15", "20", "25"], 3, "5 squared means 5 x 5, which equals 25."],
    ["m6", "What is the perimeter of a square with side length 4?", ["8", "12", "16", "20"], 2, "A square has four equal sides, so 4 + 4 + 4 + 4 = 16."],
    ["m7", "What is half of 64?", ["16", "24", "32", "36"], 2, "Half of 64 is 32."],
    ["m8", "What is 11 + 14?", ["23", "24", "25", "26"], 2, "11 + 14 = 25."],
    ["m9", "What is 3/4 written as a decimal?", ["0.25", "0.5", "0.75", "0.8"], 2, "Three quarters is 0.75."],
    ["m10", "How many degrees are in a right angle?", ["45", "60", "90", "120"], 2, "A right angle measures 90 degrees."],
    ["m11", "What is 7 x 8?", ["54", "56", "58", "64"], 1, "7 times 8 equals 56."],
    ["m12", "What is 81 divided by 9?", ["7", "8", "9", "10"], 2, "81 divided by 9 equals 9."],
    ["m13", "What is the next number in the pattern 2, 4, 6, 8, __?", ["9", "10", "11", "12"], 1, "The pattern increases by 2 each time, so the next number is 10."],
    ["m14", "What is the area of a rectangle with length 6 and width 3?", ["9", "12", "18", "24"], 2, "Area equals length multiplied by width: 6 x 3 = 18."],
    ["m15", "What is 100 - 37?", ["53", "63", "67", "73"], 1, "100 - 37 = 63."],
    ["m16", "What is 0.5 as a fraction in simplest form?", ["1/4", "1/2", "2/3", "3/4"], 1, "0.5 equals one half."],
    ["m17", "If a triangle has angles of 50 degrees and 60 degrees, what is the third angle?", ["60", "70", "80", "90"], 1, "Triangle angles add to 180 degrees, so 180 - 110 = 70."],
    ["m18", "What is 13 + 19?", ["30", "31", "32", "33"], 2, "13 + 19 = 32."],
    ["m19", "What is 144 divided by 12?", ["10", "11", "12", "13"], 2, "144 divided by 12 equals 12."],
    ["m20", "Which number is a prime number?", ["9", "15", "17", "21"], 2, "17 is prime because it has only two factors: 1 and 17."],
    ["m21", "What is 25 percent of 200?", ["25", "40", "50", "75"], 2, "25 percent of 200 equals 50."],
    ["m22", "What is the mean of 4, 6, and 8?", ["5", "6", "7", "8"], 1, "The mean is (4 + 6 + 8) / 3 = 6."],
    ["m23", "How many sides does a hexagon have?", ["5", "6", "7", "8"], 1, "A hexagon has six sides."],
    ["m24", "What is 2 to the power of 5?", ["16", "24", "32", "64"], 2, "2 multiplied by itself five times equals 32."],
    ["m25", "What is 18 - 9?", ["7", "8", "9", "10"], 2, "18 - 9 = 9."],
    ["m26", "What is the value of pi rounded to two decimal places?", ["3.12", "3.14", "3.16", "3.18"], 1, "Pi rounded to two decimal places is 3.14."],
    ["m27", "What is 45 + 27?", ["70", "71", "72", "73"], 2, "45 + 27 = 72."],
    ["m28", "What is one quarter of 80?", ["10", "15", "20", "25"], 2, "One quarter of 80 is 20."],
    ["m29", "How many centimeters are in 2 meters?", ["20", "200", "2000", "20000"], 1, "There are 100 centimeters in 1 meter, so 2 meters is 200 centimeters."],
    ["m30", "What is the sum of the angles in any triangle?", ["90 degrees", "120 degrees", "180 degrees", "360 degrees"], 2, "The interior angles of any triangle add up to 180 degrees."]
  ];

  mathRows.forEach(([id, question, choices, answer, fact]) => add(id, "math", question, choices, answer, fact));

  window.JO_QUIZ_BANK = bank;
})();
