
(()=>{"use strict";
const K="jo_admin_token",PS=25;
const s={token:sessionStorage.getItem(K)||"",section:"overview",pages:{users:0,conversations:0,media:0,referrals:0},hasMore:{users:false,conversations:false,media:false,referrals:false},totals:{users:0,conversations:0,media:0,referrals:0},loaded:{overview:false,users:false,conversations:false,media:false,referrals:false,engagement:false,botStatus:false,settings:false,logs:false}};
const T={overview:"Overview",users:"Users",conversations:"Conversations",media:"Media",referrals:"Referrals",engagement:"Broadcast / Engagement","bot-status":"Bot Status",settings:"Settings",logs:"Logs / Errors"};
const e={
loginOverlay:g("loginOverlay"),loginForm:g("loginForm"),loginToken:g("loginToken"),telegramLoginBtn:g("telegramLoginBtn"),loginError:g("loginError"),shell:g("shell"),nav:[...document.querySelectorAll(".nav-btn")],menuToggle:g("menuToggle"),pageTitle:g("pageTitle"),refreshBtn:g("refreshBtn"),logoutBtn:g("logoutBtn"),authChip:g("authChip"),
overviewSummary:g("overviewSummary"),overviewRecent:g("overviewRecent"),
usersSearch:g("usersSearch"),usersActiveWindow:g("usersActiveWindow"),usersApply:g("usersApply"),usersList:g("usersList"),usersPrev:g("usersPrev"),usersNext:g("usersNext"),usersPageInfo:g("usersPageInfo"),
convSearch:g("convSearch"),convType:g("convType"),convFrontend:g("convFrontend"),convDateFrom:g("convDateFrom"),convDateTo:g("convDateTo"),convApply:g("convApply"),conversationsList:g("conversationsList"),convPrev:g("convPrev"),convNext:g("convNext"),convPageInfo:g("convPageInfo"),
mediaSearch:g("mediaSearch"),mediaApply:g("mediaApply"),mediaSummary:g("mediaSummary"),mediaList:g("mediaList"),mediaPrev:g("mediaPrev"),mediaNext:g("mediaNext"),mediaPageInfo:g("mediaPageInfo"),
refSearch:g("refSearch"),refApply:g("refApply"),refSummary:g("refSummary"),refList:g("refList"),refPrev:g("refPrev"),refNext:g("refNext"),refPageInfo:g("refPageInfo"),
engEnabled:g("engEnabled"),engInactivity:g("engInactivity"),engCooldown:g("engCooldown"),engBatch:g("engBatch"),engMessage:g("engMessage"),engSave:g("engSave"),engUpdated:g("engUpdated"),
botStatusRefresh:g("botStatusRefresh"),botStatusGrid:g("botStatusGrid"),botWarnings:g("botWarnings"),
statusInfo:g("statusInfo"),settingsToken:g("settingsToken"),settingsTokenSave:g("settingsTokenSave"),settingsTokenTest:g("settingsTokenTest"),settingsLogout:g("settingsLogout"),
logsLevel:g("logsLevel"),logsSearch:g("logsSearch"),logsLimit:g("logsLimit"),logsApply:g("logsApply"),logsOutput:g("logsOutput"),toast:g("toast")
};
function g(id){return document.getElementById(id)}
const h=v=>String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#39;");
const n=v=>{const p=Number(v??0);return Number.isFinite(p)?p.toLocaleString():"0"};
const d=v=>{if(!v)return"-";const p=new Date(v);return Number.isNaN(p.getTime())?String(v):p.toLocaleString()};
const u=r=>{const un=String(r.username||"").trim(),f=String(r.first_name||"").trim(),l=String(r.last_name||"").trim(),nm=[f,l].filter(Boolean).join(" ").trim(),id=un?`@${un}`:nm||"unknown";return `${id} (${r.telegram_id||"?"})`};
function toast(m,err=false){if(!e.toast)return;e.toast.hidden=false;e.toast.textContent=String(m||"Done.");e.toast.style.background=err?"#8f1d14":"#16202b";clearTimeout(toast.t);toast.t=setTimeout(()=>e.toast.hidden=true,3000)}
function chip(ok){if(!e.authChip)return;e.authChip.textContent=ok?"Authorized":"Locked";e.authChip.style.background=ok?"#e5f7ee":"#f3f4f6"}
function showLogin(msg=""){if(e.loginOverlay)e.loginOverlay.hidden=false;if(e.shell)e.shell.hidden=true;if(e.loginError){e.loginError.hidden=!msg;e.loginError.textContent=msg}chip(false)}
function hideLogin(){if(e.loginOverlay)e.loginOverlay.hidden=true;if(e.shell)e.shell.hidden=false;if(e.loginError){e.loginError.hidden=true;e.loginError.textContent=""}chip(true)}
function headers(auth=true){const x={Accept:"application/json"};if(auth&&s.token)x["x-admin-token"]=s.token;return x}
async function req(path,{method="GET",params=null,body=null,auth=true,extra={}}={}){const url=new URL(path,location.origin);url.searchParams.set("_ts",String(Date.now()));if(params)for(const[k,v]of Object.entries(params))if(v!==undefined&&v!==null&&v!=="")url.searchParams.set(k,String(v));const hd={...headers(auth),...extra};if(method!=="GET"&&body!==null)hd["Content-Type"]="application/json";const res=await fetch(url.toString(),{method,headers:hd,body:method!=="GET"&&body!==null?JSON.stringify(body):undefined,credentials:"same-origin",cache:"no-store"});const raw=await res.text();let p={};if(raw)try{p=JSON.parse(raw)}catch{p={error:raw.slice(0,300)}};if(!res.ok){const er=new Error(String(p.error||p.detail||p.message||`Request failed (${res.status}).`));er.status=res.status;er.payload=p;throw er}return p}
function authErr(er){if(!er||(er.status!==401&&er.status!==403))return false;sessionStorage.removeItem(K);s.token="";showLogin("Session expired. Please login again.");toast("Admin session expired.",true);return true}
function metric(l,v){return `<article class="metric"><p class="label">${h(l)}</p><p class="value">${h(v)}</p></article>`}
function empty(c,m){if(c)c.innerHTML=`<article class="list-item"><p>${h(m)}</p></article>`}
function mediaRef(it){const pr=String(it.preview_ref||"").trim();if(pr)return pr;const mu=String(it.media_url||"").trim();if(mu)return mu;const sp=String(it.storage_path||"").trim();if(sp.startsWith("telegram_file:"))return `/api/admin/media/proxy?ref=${encodeURIComponent(sp)}`;return sp||""}
function sectionEl(nm){return g(`section-${nm}`)}
function setSection(nm){s.section=nm;for(const b of e.nav)b.classList.toggle("active",b.dataset.section===nm);for(const k of Object.keys(T)){const p=sectionEl(k);if(p)p.classList.toggle("active",k===nm)}if(e.pageTitle)e.pageTitle.textContent=T[nm]||"Admin"}
function markStale(){for(const k of Object.keys(s.loaded))s.loaded[k]=false}
function resetPg(k){s.pages[k]=0;s.hasMore[k]=false}
function pageInfo(k,total){const p=s.pages[k]+1,tp=Math.max(1,Math.ceil(total/PS));return `Page ${p} / ${tp} (${n(total)} total)`}
function copy(t){const v=String(t||"");if(!v)return;if(navigator.clipboard&&navigator.clipboard.writeText){navigator.clipboard.writeText(v).then(()=>toast("Copied."),()=>toast("Copy failed.",true));return}toast("Copy not available.",true)}
async function loadOverview(force=false){if(!force&&s.loaded.overview)return;try{const p=await req("/api/admin/overview"),sm=p.summary||{},m=[["Unique users",n(sm.unique_users)],["Started users",n(sm.total_started_users)],["Active users",n(sm.active_users)],["Blocked/unreachable",n(sm.blocked_users)],["New users today",n(sm.new_users_today)],["New users this week",n(sm.new_users_week)],["Referrals",n(sm.referrals_total)],["Messages",n(sm.total_messages)],["Images",n(sm.total_images)]];if(e.overviewSummary)e.overviewSummary.innerHTML=m.map(x=>metric(x[0],x[1])).join("");const rows=Array.isArray(p.recent_activity)?p.recent_activity:[];if(!rows.length)empty(e.overviewRecent,"No recent activity.");else if(e.overviewRecent)e.overviewRecent.innerHTML=rows.map(it=>`<article class="list-item"><div class="row-head"><h4>${h(u(it))}</h4><button class="btn small copy-btn" data-copy="${h(it.preview||it.text_content||"")}">Copy</button></div><p>${h(it.preview||"-")}</p><div class="list-meta"><span>${h(d(it.created_at))}</span><span>Type: ${h(it.message_type||"-")}</span><span>Feature: ${h(it.feature_used||"-")}</span><span>Frontend: ${h(it.frontend_source||"-")}</span><span>Status: ${it.success?"success":"failed"}</span></div></article>`).join("");s.loaded.overview=true}catch(er){if(authErr(er))return;empty(e.overviewRecent,"Failed to load overview.");toast(er.message||"Failed to load overview.",true)}}

async function loadUsers(force=false){if(!force&&s.loaded.users)return;try{const p=await req("/api/admin/users",{params:{limit:PS,offset:s.pages.users*PS,search:e.usersSearch?e.usersSearch.value.trim():"",active_days:e.usersActiveWindow?e.usersActiveWindow.value:"7"}}),it=Array.isArray(p.items)?p.items:[];s.totals.users=Number(p.total||0);s.hasMore.users=Boolean(p.has_more);if(!it.length)empty(e.usersList,"No users found.");else if(e.usersList)e.usersList.innerHTML=it.map(r=>`<article class="list-item"><div class="row-head"><h4>${h(u(r))}</h4><span class="chip ${r.is_blocked?"danger-chip":r.is_active?"ok-chip":"muted-chip"}">${r.is_blocked?"blocked":r.is_active?"active":"inactive"}</span></div><div class="list-meta"><span>First seen: ${h(d(r.first_seen_at))}</span><span>Last seen: ${h(d(r.last_seen_at))}</span><span>Started: ${r.has_started?"yes":"no"}</span><span>Messages: ${h(n(r.total_messages))}</span><span>Images: ${h(n(r.total_images))}</span><span>Unreachable: ${h(n(r.unreachable_count))}</span><span>Referral code: ${h(r.referral_code||"-")}</span><span>Referred by: ${h(r.referred_by||"-")}</span></div>${r.last_delivery_error?`<p class="error">Last delivery error: ${h(r.last_delivery_error)}</p>`:""}</article>`).join("");if(e.usersPageInfo)e.usersPageInfo.textContent=pageInfo("users",s.totals.users);if(e.usersPrev)e.usersPrev.disabled=s.pages.users<=0;if(e.usersNext)e.usersNext.disabled=!s.hasMore.users;s.loaded.users=true}catch(er){if(authErr(er))return;empty(e.usersList,"Failed to load users.");toast(er.message||"Failed to load users.",true)}}

async function loadConversations(force=false){if(!force&&s.loaded.conversations)return;try{const p=await req("/api/admin/messages",{params:{limit:PS,offset:s.pages.conversations*PS,search:e.convSearch?e.convSearch.value.trim():"",feature_used:e.convType?e.convType.value:"all",frontend_source:e.convFrontend?e.convFrontend.value:"all",date_from:e.convDateFrom?e.convDateFrom.value:"",date_to:e.convDateTo?e.convDateTo.value:""}}),it=Array.isArray(p.items)?p.items:[];s.totals.conversations=Number(p.total||0);s.hasMore.conversations=Boolean(p.has_more);if(!it.length)empty(e.conversationsList,"No conversations found.");else if(e.conversationsList)e.conversationsList.innerHTML=it.map(r=>{const pref=mediaRef(r),img=String(r.media_type||"").toLowerCase().startsWith("image"),tx=[`User: ${r.user_message||r.text_content||""}`,`Assistant: ${r.bot_reply||""}`].filter(Boolean).join("\n\n");return `<article class="list-item"><div class="row-head"><h4>${h(u(r))}</h4><button class="btn small copy-btn" data-copy="${h(tx)}">Copy chat</button></div><p><strong>User:</strong> ${h(r.user_message||r.text_content||"-")}</p><p><strong>Assistant:</strong> ${h(r.bot_reply||"-")}</p>${img&&pref?`<img class="media-thumb" src="${h(pref)}" alt="Conversation media" loading="lazy">`:""}<div class="list-meta"><span>${h(d(r.created_at))}</span><span>Feature: ${h(r.feature_used||"-")}</span><span>Frontend: ${h(r.frontend_source||"-")}</span><span>Type: ${h(r.message_type||"-")}</span><span>Conversation: ${h(r.conversation_id||"-")}</span><span>Model: ${h(r.model_used||"-")}</span><span>Status: ${r.success?"success":"failed"}</span></div>${r.media_error_reason?`<p class="error">Media issue: ${h(r.media_error_reason)}</p>`:""}</article>`}).join("");if(e.convPageInfo)e.convPageInfo.textContent=pageInfo("conversations",s.totals.conversations);if(e.convPrev)e.convPrev.disabled=s.pages.conversations<=0;if(e.convNext)e.convNext.disabled=!s.hasMore.conversations;s.loaded.conversations=true}catch(er){if(authErr(er))return;empty(e.conversationsList,"Failed to load conversations.");toast(er.message||"Failed to load conversations.",true)}}
async function loadMedia(force=false){if(!force&&s.loaded.media)return;try{const p=await req("/api/admin/media",{params:{limit:PS,offset:s.pages.media*PS,search:e.mediaSearch?e.mediaSearch.value.trim():""}}),sm=p.summary||{},it=Array.isArray(p.items)?p.items:[];s.totals.media=Number(p.total||0);s.hasMore.media=Boolean(p.has_more);if(e.mediaSummary)e.mediaSummary.innerHTML=[metric("Total images",n(sm.total_images)),metric("Successful images",n(sm.successful_images)),metric("Images last 7 days",n(sm.images_last_7_days))].join("");if(!it.length)empty(e.mediaList,"No media records found.");else if(e.mediaList)e.mediaList.innerHTML=it.map(r=>{const pref=mediaRef(r),why=r.media_error_reason||r.media_status||"media unavailable";return `<article class="list-item"><div class="row-head"><h4>${h(u(r))}</h4><span class="chip ${r.success?"ok-chip":"danger-chip"}">${r.success?"success":"failed"}</span></div>${pref?`<img class="media-thumb" src="${h(pref)}" alt="Media preview" loading="lazy">`:`<p class="error">No preview: ${h(why)}</p>`}<p><strong>Prompt:</strong> ${h(r.prompt||r.text_content||"-")}</p><div class="list-meta"><span>${h(d(r.created_at))}</span><span>Origin: ${h(r.media_origin||"-")}</span><span>Provider: ${h(r.provider_source||"-")}</span><span>MIME: ${h(r.mime_type||"-")}</span><span>Size: ${h(r.media_width||"-")}x${h(r.media_height||"-")}</span><span>URL: ${h(r.media_url||"-")}</span><span>Storage: ${h(r.storage_path||"-")}</span></div></article>`}).join("");if(e.mediaPageInfo)e.mediaPageInfo.textContent=pageInfo("media",s.totals.media);if(e.mediaPrev)e.mediaPrev.disabled=s.pages.media<=0;if(e.mediaNext)e.mediaNext.disabled=!s.hasMore.media;s.loaded.media=true}catch(er){if(authErr(er))return;empty(e.mediaList,"Failed to load media.");toast(er.message||"Failed to load media.",true)}}

async function loadReferrals(force=false){if(!force&&s.loaded.referrals)return;try{const p=await req("/api/admin/referrals",{params:{limit:PS,offset:s.pages.referrals*PS,search:e.refSearch?e.refSearch.value.trim():""}}),sm=p.summary||{},it=Array.isArray(p.items)?p.items:[];s.totals.referrals=Number(p.total||0);s.hasMore.referrals=Boolean(p.has_more);if(e.refSummary)e.refSummary.innerHTML=[metric("Total referrals",n(sm.total_referrals)),metric("Unique inviters",n(sm.unique_inviters)),metric("Unique invitees",n(sm.unique_invitees))].join("");if(!it.length)empty(e.refList,"No referral records found.");else if(e.refList)e.refList.innerHTML=it.map(r=>`<article class="list-item"><div class="row-head"><h4>${h(r.referral_code||"-")}</h4><span class="chip muted-chip">${h(r.frontend_source||"unknown")}</span></div><p><strong>Inviter:</strong> ${h(r.inviter_username?`@${r.inviter_username}`:r.inviter_first_name||"unknown")} (${h(r.inviter_telegram_id||"-")})<br><strong>Invitee:</strong> ${h(r.invitee_username?`@${r.invitee_username}`:r.invitee_first_name||"unknown")} (${h(r.invitee_telegram_id||"-")})</p><div class="list-meta"><span>${h(d(r.created_at))}</span><span>ID: ${h(r.id||"-")}</span></div></article>`).join("");if(e.refPageInfo)e.refPageInfo.textContent=pageInfo("referrals",s.totals.referrals);if(e.refPrev)e.refPrev.disabled=s.pages.referrals<=0;if(e.refNext)e.refNext.disabled=!s.hasMore.referrals;s.loaded.referrals=true}catch(er){if(authErr(er))return;empty(e.refList,"Failed to load referrals.");toast(er.message||"Failed to load referrals.",true)}}

async function loadEngagement(force=false){if(!force&&s.loaded.engagement)return;try{const p=await req("/api/admin/engagement"),c=p.config||{};if(e.engEnabled)e.engEnabled.checked=Boolean(c.enabled);if(e.engInactivity)e.engInactivity.value=String(c.inactivity_minutes||240);if(e.engCooldown)e.engCooldown.value=String(c.cooldown_minutes||720);if(e.engBatch)e.engBatch.value=String(c.batch_size||30);if(e.engMessage)e.engMessage.value=String(c.message_template||"");if(e.engUpdated)e.engUpdated.textContent=p.updated_at?`Last updated: ${d(p.updated_at)}`:"Using defaults";s.loaded.engagement=true}catch(er){if(authErr(er))return;toast(er.message||"Failed to load engagement settings.",true)}}

async function saveEngagement(){const b={enabled:Boolean(e.engEnabled&&e.engEnabled.checked),inactivity_minutes:Number(e.engInactivity?e.engInactivity.value:240),cooldown_minutes:Number(e.engCooldown?e.engCooldown.value:720),batch_size:Number(e.engBatch?e.engBatch.value:30),message_template:e.engMessage?e.engMessage.value.trim():""};try{const p=await req("/api/admin/engagement",{method:"POST",body:b});if(e.engUpdated)e.engUpdated.textContent=p.updated_at?`Last updated: ${d(p.updated_at)}`:"Saved";toast("Engagement settings saved.");s.loaded.engagement=true}catch(er){if(authErr(er))return;toast(er.message||"Failed to save engagement settings.",true)}}

async function loadBotStatus(force=false){if(!force&&s.loaded.botStatus)return;try{const p=await req("/api/admin/bot-status"),m=[["Runtime ready",p.runtime_ready?"yes":"no"],["Telegram ready",p.telegram_ready?"yes":"no"],["Webhook configured",p.webhook_configured?"yes":"no"],["Menu button configured",p.menu_button_configured?"yes":"no"],["Startup task running",p.startup_task_running?"yes":"no"],["Keepalive task",p.keepalive_task_running?"running":"stopped"],["Heartbeat task",p.heartbeat_task_running?"running":"stopped"],["Engagement task",p.engagement_task_running?"running":"stopped"],["Uptime seconds",String(p.uptime_seconds||0)]];if(e.botStatusGrid)e.botStatusGrid.innerHTML=m.map(x=>metric(x[0],x[1])).join("");const ws=[];if(p.last_startup_error)ws.push(`Last startup error: ${p.last_startup_error}`);if(Array.isArray(p.startup_warnings))for(const w of p.startup_warnings)if(w)ws.push(String(w));if(!ws.length)empty(e.botWarnings,"No runtime warnings.");else if(e.botWarnings)e.botWarnings.innerHTML=ws.map(w=>`<article class="list-item"><p>${h(w)}</p></article>`).join("");s.loaded.botStatus=true}catch(er){if(authErr(er))return;empty(e.botWarnings,"Failed to load bot status.");toast(er.message||"Failed to load bot status.",true)}}

async function loadSettings(force=false){if(!force&&s.loaded.settings)return;try{const p=await req("/api/admin/status",{auth:false}),x=[`Admin token configured: ${p.token_configured?"yes":"no"}`,`Telegram admin login: ${p.telegram_auth_enabled?"enabled":"disabled"}`,`Allowlist count: ${n(p.allowlist_count)}`,`Admin data service: ${p.service_enabled?"enabled":"disabled"}`];if(!p.service_enabled&&p.service_reason)x.push(`Reason: ${p.service_reason}`);if(e.statusInfo)e.statusInfo.textContent=x.join(" | ");if(e.settingsToken)e.settingsToken.value=s.token||"";s.loaded.settings=true}catch{if(e.statusInfo)e.statusInfo.textContent="Failed to load settings status."}}

async function loadLogs(force=false){if(!force&&s.loaded.logs)return;try{const p=await req("/api/admin/logs",{params:{level:e.logsLevel?e.logsLevel.value:"",search:e.logsSearch?e.logsSearch.value.trim():"",limit:e.logsLimit?e.logsLimit.value:"200"}}),it=Array.isArray(p.items)?p.items:[];if(e.logsOutput)e.logsOutput.textContent=it.length?it.join("\n"):"No logs for current filters.";s.loaded.logs=true}catch(er){if(authErr(er))return;if(e.logsOutput)e.logsOutput.textContent=`Failed to load logs. ${er.message||""}`;toast(er.message||"Failed to load logs.",true)}}

async function loadSection(nm,force=false){if(nm==="overview")return loadOverview(force);if(nm==="users")return loadUsers(force);if(nm==="conversations")return loadConversations(force);if(nm==="media")return loadMedia(force);if(nm==="referrals")return loadReferrals(force);if(nm==="engagement")return loadEngagement(force);if(nm==="bot-status")return loadBotStatus(force);if(nm==="settings")return loadSettings(force);if(nm==="logs")return loadLogs(force)}
function tgCtx(){const tg=window.Telegram&&window.Telegram.WebApp?window.Telegram.WebApp:null;if(!tg)return{initData:"",telegramId:""};const initData=typeof tg.initData==="string"?tg.initData.trim():"",u=tg.initDataUnsafe&&typeof tg.initDataUnsafe==="object"?tg.initDataUnsafe:null,telegramId=u&&u.user&&typeof u.user.id!=="undefined"?String(u.user.id):"";return{initData,telegramId}}
async function verify(){const p=await req("/api/admin/auth",{auth:Boolean(s.token)});if(p.ok!==true)throw new Error("Admin session check failed.");return p}
async function loginToken(raw){const t=String(raw||"").trim();if(!t){showLogin("Admin token is required.");return}s.token=t;try{await verify();sessionStorage.setItem(K,t);if(e.settingsToken)e.settingsToken.value=t;hideLogin();markStale();await loadSection(s.section,true);toast("Admin login successful.")}catch(er){s.token="";sessionStorage.removeItem(K);showLogin(er.message||"Unauthorized admin token.");toast(er.message||"Login failed.",true)}}
async function loginTg(){const c=tgCtx();if(!c.initData){toast("Open this admin panel in Telegram WebApp for Telegram login.",true);return}try{const p=await req("/api/admin/auth/telegram",{auth:false,extra:{"x-telegram-init-data":c.initData,"x-telegram-id":c.telegramId}}),t=String(p.token||"").trim();if(t){s.token=t;sessionStorage.setItem(K,t)}await verify();hideLogin();markStale();await loadSection(s.section,true);toast("Telegram admin login successful.")}catch(er){showLogin(er.message||"Telegram admin login failed.");toast(er.message||"Telegram admin login failed.",true)}}
async function logout(){try{await req("/api/admin/auth/logout",{method:"POST",body:{},auth:Boolean(s.token)})}catch{}s.token="";sessionStorage.removeItem(K);showLogin("Logged out.");toast("Logged out.")}
async function refresh(){s.loaded[s.section==="bot-status"?"botStatus":s.section]=false;await loadSection(s.section,true)}
function bind(){for(const b of e.nav)b.addEventListener("click",async()=>{const nm=b.dataset.section||"overview";setSection(nm);document.body.classList.remove("sidebar-open");await loadSection(nm)});if(e.menuToggle)e.menuToggle.addEventListener("click",()=>document.body.classList.toggle("sidebar-open"));if(e.loginForm)e.loginForm.addEventListener("submit",async(ev)=>{ev.preventDefault();await loginToken(e.loginToken?e.loginToken.value:"")});if(e.telegramLoginBtn)e.telegramLoginBtn.addEventListener("click",()=>loginTg());if(e.logoutBtn)e.logoutBtn.addEventListener("click",()=>logout());if(e.settingsLogout)e.settingsLogout.addEventListener("click",()=>logout());if(e.refreshBtn)e.refreshBtn.addEventListener("click",()=>refresh());if(e.usersApply)e.usersApply.addEventListener("click",async()=>{resetPg("users");s.loaded.users=false;await loadUsers(true)});if(e.convApply)e.convApply.addEventListener("click",async()=>{resetPg("conversations");s.loaded.conversations=false;await loadConversations(true)});if(e.mediaApply)e.mediaApply.addEventListener("click",async()=>{resetPg("media");s.loaded.media=false;await loadMedia(true)});if(e.refApply)e.refApply.addEventListener("click",async()=>{resetPg("referrals");s.loaded.referrals=false;await loadReferrals(true)});if(e.engSave)e.engSave.addEventListener("click",()=>saveEngagement());if(e.botStatusRefresh)e.botStatusRefresh.addEventListener("click",async()=>{s.loaded.botStatus=false;await loadBotStatus(true)});if(e.settingsTokenSave)e.settingsTokenSave.addEventListener("click",()=>{const t=e.settingsToken?e.settingsToken.value.trim():"";if(!t){toast("Token is empty.",true);return}s.token=t;sessionStorage.setItem(K,t);if(e.loginToken)e.loginToken.value=t;toast("Token saved for this browser session.")});if(e.settingsTokenTest)e.settingsTokenTest.addEventListener("click",()=>loginToken(e.settingsToken?e.settingsToken.value.trim():""));if(e.logsApply)e.logsApply.addEventListener("click",async()=>{s.loaded.logs=false;await loadLogs(true)});
if(e.usersPrev)e.usersPrev.addEventListener("click",async()=>{if(s.pages.users<=0)return;s.pages.users--;s.loaded.users=false;await loadUsers(true)});if(e.usersNext)e.usersNext.addEventListener("click",async()=>{if(!s.hasMore.users)return;s.pages.users++;s.loaded.users=false;await loadUsers(true)});
if(e.convPrev)e.convPrev.addEventListener("click",async()=>{if(s.pages.conversations<=0)return;s.pages.conversations--;s.loaded.conversations=false;await loadConversations(true)});if(e.convNext)e.convNext.addEventListener("click",async()=>{if(!s.hasMore.conversations)return;s.pages.conversations++;s.loaded.conversations=false;await loadConversations(true)});
if(e.mediaPrev)e.mediaPrev.addEventListener("click",async()=>{if(s.pages.media<=0)return;s.pages.media--;s.loaded.media=false;await loadMedia(true)});if(e.mediaNext)e.mediaNext.addEventListener("click",async()=>{if(!s.hasMore.media)return;s.pages.media++;s.loaded.media=false;await loadMedia(true)});
if(e.refPrev)e.refPrev.addEventListener("click",async()=>{if(s.pages.referrals<=0)return;s.pages.referrals--;s.loaded.referrals=false;await loadReferrals(true)});if(e.refNext)e.refNext.addEventListener("click",async()=>{if(!s.hasMore.referrals)return;s.pages.referrals++;s.loaded.referrals=false;await loadReferrals(true)});
document.addEventListener("click",ev=>{const t=ev.target;if(!(t instanceof HTMLElement))return;const b=t.closest(".copy-btn");if(!b)return;copy(b.getAttribute("data-copy")||"")})}
async function init(){setSection("overview");bind();await loadSettings(true);if(s.token){if(e.loginToken)e.loginToken.value=s.token;if(e.settingsToken)e.settingsToken.value=s.token;try{await verify();hideLogin();await loadSection("overview",true);return}catch{s.token="";sessionStorage.removeItem(K)}}try{await verify();hideLogin();await loadSection("overview",true);toast("Admin session restored.");return}catch{showLogin()}}
window.addEventListener("DOMContentLoaded",init);
})();
